Story Information Widget
PrincetonPEMM/pemm-website pull request #27
Opened 2022-06-10 12:39 UTC by issacjohannli

- Added data types for story information widget in stories.ts
- Added test data for story 13 in story13.ts
- Implemented story information widget in [canonicalId].tsx

2022-06-10 14:54 UTC, henokalem requested changes

2022-06-13 16:29 UTC, issacjohannli commented on src/pages/stories/[canonicalId].tsx
> +              <Typography variant="body2"> <b>Story type:</b> {data.story.type_of_story}</Typography>
Updated. HTML is moved into the storyInformationWidget.tsx component.

2022-06-13 18:59 UTC, henokalem commented on src/components/types/stories.ts
> +    canoncial_incipit?: string | null,
This also needs to get updated

2022-06-13 19:10 UTC, issacjohannli commented on src/components/types/stories.ts
> +    canoncial_incipit?: string | null,
Typographical error is fixed

2022-06-13 19:19 UTC, henokalem approved these changes

2022-06-14 08:46 UTC, merged