Generated text cleanup
PrincetonPEMM/pemm-website pull request #54
Opened 2022-09-26 20:43 UTC by ayo-gb

Underlined the main points + added * text

2022-09-30 15:18 UTC, henokalem requested changes
Can you resolve the merge conflicts? I think your branch is out of sync with main branch, it won't merge this pull request.

2022-10-10 15:23 UTC, ayo-gb commented
Merge Conflicts resolved & further instruction/data needed to implement the post-life miracle and standalone sentences in section example shown in the ticket. Otherwise, the current formatting matches.

2022-10-10 15:54 UTC, ayo-gb commented
I believe the information for the readings_dates of the stories (Column AC in the canonical story sheet) needs to be added to the API for the sentence to show.

2022-10-20 12:03 UTC, henokalem approved these changes

2022-10-20 12:03 UTC, merged